### ISSUE TITLE
Events aus der Datenbank bekommen

### ISSUE THREAD

**Issue by tomegen** [bendredi/de.thi.jbsa.ss2020.studychat#1]
Ich verstehe leider nicht ganz wie ich die Events aus der postgres-Datenbank bekomme und wie ich die events in der MongoDB verändere.

Muss ich bei der postgres-Datenbank wirklich alle Events heraussuchen, nach MessagePostedEvent filtern und den json-value in ein MessagePostedEvent umwandeln oder geht das einfacher?

Das Gleiche bei der MongoDB. Muss ich dort auch alle Einträge erst filtern, dann den Eintrag löschen und wieder neu speichern oder geht das einfacher?

**Comment by WhiteHatTux** [comment]
Events aus der postgres Datenbank können mit dem EventRepository abgeholt werden.
Einige Methoden sind schon automatisch da (save, findall), aber weitere Methoden, auch mit Filtermöglichkeiten können über das [EventRepository](https://github.com/bendredi/de.thi.jbsa.ss2020.studychat/blob/master/b-domain-handler/src/main/java/de/thi/jbsa/prototype/repository/EventRepository.java) nachdefiniert werden. 

Spring bietet hierfür eine ausführliche Dokumentation: 
https://docs.spring.io/spring-data/data-commons/docs/1.6.1.RELEASE/reference/html/repositories.html

Tatsächlich funktionierte das Folgende nicht richtig, weil wir die EventName in der Datenbank fälschlicherweise als varchar ausgewiesen war. Ich habe das mit dem commit [e8c6c93](https://github.com/bendredi/de.thi.jbsa.ss2020.studychat/commit/e8c6c938ff1c21bfbee5883dfaec20c2851ee6af) behoben. 
Das Abholen nach Eventtyp geht direkt mit einer solchen Abfrage. 
`EventEntity findFirstByEventNameOrderByIdDesc(EventName eventname);`
Hier kriege ich das letzte Event, welches als EventName den übergebenen Parameter hat.
Wenn ich jetzt auch noch wissen will, von wem die Nachricht geschickt wurde wird es schon etwas schwieriger. Eigentlich wäre es besser diesen Wert nicht nur im "value" zu haben. Um jetzt aber grosse Refactorings zu vermeiden können wir der Datenbank einfach sagen, dass sie uns bitte den Wert durchsuchen soll. 
`EventEntity findFirstByEventNameAndValueContainingOrderByIdDesc(EventName eventname, String containedInValue);`
Hier erkennt Spring welcher Parameter zu welchem Teil der Query gehört und erstellt daraus die eigentliche SQL-Abfrage.

Sehr Ähnliches gilt für die MongoDB. Im [MessageRepository](https://github.com/bendredi/de.thi.jbsa.ss2020.studychat/blob/master/b-read-api/src/main/java/de/thi/jbsa/prototype/repository/MessageRepository.java) ist sogar schon eine solche Methode definiert.

Auch hier ist die Spring Dokumentation sehr hilfreich:
https://docs.spring.io/spring-data/mongodb/docs/2.1.10.RELEASE/reference/html/#repositories.limit-query-result

Um ein update zu machen. holst du einfach die gesuchte Entity mit einer der Repositorymethoden aus der Datenbank, veränderst sie und nutzt "repository.save()" um die Entity wieder zurück zu schreiben. Hibernate erkennt, wenn die Entity schon eine "id" hat und speichert dann kein neues Event, sondern macht ein update.

**Comment by tomegen** [comment]
Dankeschön, bei mir klappts jetzt.

Bis morgen :)
