### ISSUE TITLE
private Frage: UI-Framework für Hybrid Apps

### ISSUE THREAD

**Issue by tomegen** [bendredi/de.thi.jbsa.ss2020.studychat#2]
Habe nochmal eine andere Frage, die nichts mit Studychat zu tun hat, hoffe das ist auch in Ordnung.

Ich habe eventuell vor, mit einer Kommilitonin eine App zu entwickeln, die als Backend SpringBoot verwendet. Im Prinzip genau so wie wir es im Studychat gemacht haben. 

Welches UI-Framework verwendet man denn da am Besten um Kompatibilität für Android und IOS zu schaffen? Bzw. was habt ihr da für die Ulassa-App verwendet?
Ich hätte es vermutlich mit Flutter gemacht, aber vielleicht gibt es ja eine bessere Alternative :)

In der App soll außer einem Login, Datenbankzugriffen und ein bisschen Business-Logic nicht viel passieren. 

Danke schon mal im Voraus ;)

**Comment by WhiteHatTux** [comment]
Unsere App haben wir mit react-native entwickelt. Das wird in javascript geschrieben und lässt sich dann für die beiden mobile Plattformen kompilieren. 

Ich denke in eurem Fall würde ich flutter probieren. Wenn die App relativ simpel sein wird, dann werdet ihr keine Probleme mit fehlendem Technologiesupport in dem neuen Framework haben. Und gleichzeitig bekommt ihr einen Einblick in dart, was sich gut zu entwickeln scheint.

**Comment by tomegen** [comment]
Ok, vielen Dank für die Antwort. Dann versuchen wir es mit Flutter :)
